---
abstract: 'Perl class for reading a graph from unicode tree text format.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  Encode: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Reader-UnicodeTree
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Encode: 0
  Graph::Reader: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Graph-Reader-UnicodeTree/issues
  homepage: https://github.com/michal-josef-spacek/Graph-Reader-UnicodeTree
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Graph-Reader-UnicodeTree
version: '0.03'
